project:
  type: website

website:
  title: "My Logs"
  site-url: "https://open4177.netlify.app/"
  site-path: "/"
  navbar:
    right:
      - about.qmd
      - icon: twitter
        href: https://x.com/open4177
      - icon: linkedin
        href: https://www.linkedin.com/in/kwonhyuckmin/
  sidebar:
    contents: auto
  page-footer: "Copyright 2025, Kwon Hyuckmin" 


format:
  html:
    theme: Litera
    css: styles.css

editor: visual

