project:
  type: website

website:
  title: "My Logs"
  navbar:
    right:
      - about.qmd
      - icon: twitter
        href: https://x.com/open4177
      - icon: linkedin
        href: https://www.linkedin.com/in/kwonhyuckmin/

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

