project:
  type: website

website:
  title: "Data of Men"
  site-url: "https://dataof.men"
  site-path: "/"
  navbar:
    right:
      - about.qmd
      - icon: twitter
        href: https://x.com/open4177
      - icon: linkedin
        href: https://www.linkedin.com/in/kwonhyuckmin/
  page-footer: "Copyright 2025, dataof.men" 

format:
  html:
    theme: Litera
    css: styles.css

editor: visual

date-format: iso
